config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'products#index'

  resources :brands
  resources :products
  resources :orders
  resources :restaurants

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/views/include/_footer.html.erb
<head>
  <style>

      #footer {
          position:fixed;
          left:0px;
          bottom:0px;
          height:30px;
          width:100%;
      }
  </style>
</head>
<body>
<div class="container">
  <div class="footer">
    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item"><a href="/" class="nav-link px-2 text-muted">Главная</a></li>
          <li><%= link_to "Продукты", products_path, :class => 'nav-link px-2 text-muted' %></li>
          <li><%= link_to "Поставщики", brands_path, :class => 'nav-link px-2 text-muted' %></li>
          <li><%= link_to "Рестораны", restaurants_path, :class => 'nav-link px-2 text-muted' %></li>
          <li><%= link_to "About", brands_path, :class => 'nav-link px-2 text-muted' %></li>
        </ul>
        <p class="text-center text-muted">© 2022 Company, Inc</p>
    </footer>
  </div>
</div>
</body>

app/views/include/_header.html.erb
<header class="p-3 bg-dark text-white">
  <div class="container-fluid">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/" class="btn btn-active-light-dark text-white"><strong>Главная</strong></a></li>
        <%= link_to "Продукты", products_path, :class => 'btn btn-active-light-dark text-secondary' %>
        <%= link_to "Поставщики", brands_path, :class => 'btn btn-active-light-dark text-secondary' %>
        <%= link_to "Рестораны", restaurants_path, :class => 'btn btn-active-light-dark text-secondary' %>
        <li><a href="#" class="btn btn-active-light-dark text-secondary">About</a></li>
      </ul>

      <div class="text-end">
        <div class="navbar-text float-right">
          <% if user_signed_in? %>
            Вы вошли как <strong><%= current_user.email %></strong>
            <%= link_to "Редактирование аккаунта", edit_user_registration_path, :class => 'btn btn-active-light-dark text-secondary' %>
            <%= link_to "Корзина", orders_path, :class => 'btn btn-warning text-black' %>
            <%= link_to "Выйти", destroy_user_session_path, method: :delete, :class => "btn btn-outline-light me-2" %>
          <% else %>
            <%= link_to "Регистрация", new_user_registration_path, :class => 'btn btn-warning text-black'  %>
            <%= link_to "Войти", new_user_session_path, :class => 'btn btn-outline-light me-2'%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/include/_notification.html.erb
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger" role="alert">
      <%= alert %>
    </div>
  <% end %>